### ISSUE TITLE
Убрать магические двойки

### ISSUE THREAD

**Issue by friendlyted** [AOkhapkina/TicTacToe#18]
https://github.com/AOkhapkina/TicTacToe/blob/7ae2fab8bb648058630ba067217fee9bd787a43f/src/main/java/MainGame.java#L75

**Comment by Alima-T** [comment]
Федь, а мне двойки нужны здесь, число должно быть от 0 до 2 включительно. В этом суть метода.

**Comment by friendlyted** [comment]
Ну тогда надо и метод переписать так,чтобы он анализировал от нуля до двух,
а не ноль, один, два :)
От X до Y = for loop.
В данной игре это не важно (тут всегда три поля), но если бы мы делали
изменяемый размер доски, пришлось бы это делать. Но все равно представь, что
мы работаем с полем 5х5. Считай это заданием со звездочкой :)
