### ISSUE TITLE
Программа останавливается на неверных координатах

### ISSUE THREAD

**Issue by friendlyted** [AOkhapkina/TicTacToe#19]
При вводе координат 1 x 11 выпадает исключение 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 3
        at MainGame.main(MainGame.java:35)

**Comment by friendlyted** [comment]
Желательно разбивать коммитить каждый шаг изменений. Сделала try-catch, закоммитила, сделала do while, закоммитила. Коммиты с несколькими изменениями не очень.

**Comment by Alima-T** [comment]
Поняла, в связи с этим написала коммент с вопросом в ветке по тестированию
